---
- include_tasks:        'tasks/common/install_packages.yml'
- include_tasks:        'tasks/common/shell_commands.yml'
- include_tasks:        'tasks/common/template_files.yml'
- include_tasks:        'tasks/common/shell_commands.yml'
